### ISSUE TITLE
ListFactors fails due to JSON unmarshal to okta.UserFactor

### ISSUE THREAD

**Issue by ravenoak** [okta/okta-sdk-golang#106]
The `ListFactors` method fails with:

`json: cannot unmarshal object into Go value of type okta.UserFactor`

This is always reproducible.

**Comment by jamesgoodhouse** [comment]
Doing a little digging into the code reveals that an attempt is being made to [unmarshal the response into an interface](https://github.com/okta/okta-sdk-golang/blob/master/okta/factor.go#L78) (`UserFactor`) instead of a concrete type such as `CallFactor` or `SMSFactor`. This is not possible.

One avenue to take to fix this is to create a new concrete type and unmarshal into that. For example, instead of using `[]UserFactor`, one could create a new type—something like `type UserFactors []UserFactor`—and attach a custom `UnmarshalJSON` method to it. This custom method could inspect the given data and unmarshal into the proper concrete types.

**Comment by ravenoak** [comment]
It seems that the interfaces should implement `UnmarshalJSON` in order to properly unmarshal the profile into their respective structs.

https://endophage.com/post/golang-parse-to-interface/

**Comment by bretterer** [comment]
I believe this has been fixed and released in our v2.0.0 release.

Could you please let me know if you are still getting this issue after updating to the latest release?

**Comment by eatplaysleep** [comment]
@bretterer I can confirm it's still happening. Just upgraded my Okta Terraform provider to the most recent, which has been upgraded to use the 2.0 SDK and have started seeing the following error: 

`Error: json: cannot unmarshal array into Go value of type okta.UserType`

**Comment by bogdanprodan-okta** [comment]
@eatplaysleep could you please provide an example of the terraform resource of data so I can test and fix it?

**Comment by ejcx** [comment]
Can confirm I just ran into this issue while developing with the SDK. I am simple calling `client.Factor.ListFactors(user.Id)` and it is failing.

**Comment by bogdanprodan-okta** [comment]
Hi, @ejcx! I don't think this SDK has a `Factor` resource. I checked `UserFactor` using the latest version and it works just fine:
```
userFactors,resp, err := client.UserFactor.ListFactors(ctx, "my_user_id")
```
Could you please provide stack trace of the error you get?

**Comment by bretterer** [comment]
Closing this issue as inactive. If this is still an issue, please open a new ticket with reproduction steps and a current stack trace of the issue
