### ISSUE TITLE
Incorrect ErrorSummary provided when creating a duplicate user

### ISSUE THREAD

**Issue by tgrobinson** [okta/okta-sdk-golang#171]
Sending a request to create a user that already exists in the Okta instance returns a generic error unrelated to the cause. Triggering the error and casting this to an `okta.Error` type looks like so:
```
ErrorCode: E0000001
ErrorSummary: Api validation failed: login
ErrorCauses: [map[errorSummary:login: An object with this field already exists in the current organization]]
```

This requires manual parsing of the ErrorCauses to determine the real cause of the fault. I would expect this request to either return a separate error code for a duplicate resource such as [E0000108](https://developer.okta.com/docs/reference/error-codes/#E0000108) or have an ErrorSummary more descriptive, such as `Duplicate user/resource`.

To add rationale to this, HTTP standards dictate if a request is valid but the server rejects the data due to a conflicting resource; a HTTP response of `409 Conflict` should be thrown where as generic field validation errors sit under a `400 Bad Request`. Meaning there should be a logical way to distinguish between a malformed (incorrect format) login value and an unacceptable (duplicate) value.

**Comment by bretterer** [comment]
@tgrobinson thank you for your feedback.  I am going to request that you send this over to our support team as the error you are seeing is given to you through the SDK that is directly related to the error we receive from the API call. We do not manipulate the errors at all within the SDK. I have addressed this with the internal teams as well to help get the ball rolling.  (Internal Ref: OKTA-336189)

You can reach our support team at devex@okta.com and they will be of more assistance since this would be a required change in the API itself and not from the SDK.  Please feel free to reference this issue in your email to them.

**Comment by tgrobinson** [comment]
I raised this with the support team who looked into the issue and advised they would not fix this at the API level.
