### ISSUE TITLE
Integration Tests for Applications

### ISSUE THREAD

**Issue by bretterer** [okta/okta-sdk-golang#24]

**Comment by BrentSouza** [comment]
@bretterer Hi there I am wondering what is the plan for the different application, applicationSettings, and applicationCredentials structs, e.g.: `openIdConnectApplication`, `openIdConnectApplicationSettings`, and `oauthApplicationCredentials`. 

I am not incredibly familiar with Go, so please pardon my ignorance if the following is off the mark, but it looks like the way the `ApplicationResource` methods are setup now, it would require some level of polymorphism that's not achievable with Go structs for the different application variants to be of use. 

Will `Application` become an interface with methods to expose the relevant settings/credentials per app type? Or perhaps you'll simply collapse all fields into `Application`, `ApplicationSettings`, and `ApplicationCredentials`.

I can see that these structs were generated from the OpenAPI spec, so I'm imagining as you start into these integration tests you will tweak the output to something that's more idiomatic to Go.

My motivation for asking is that I'm interested in extending [this terraform provider](https://github.com/articulate/terraform-provider-okta) to support applications, and in doing so I've migrated the provider to use this okta sdk, instead of the one being maintained by articulate.
