### ISSUE TITLE
user auth endpoint support

### ISSUE THREAD

**Issue by cweagans** [okta/okta-sdk-golang#51]
I have some code that I wrote at work that can authenticate a user against Okta's authentication endpoint. If we opened a PR to add that support, would it be accepted? I saw the note in the readme, but it doesn't make a lot of sense to me for everyone to write their own auth code.

**Comment by samjarrett** [comment]
@cweagans any chance in the interim you'd consider open sourcing it?

**Comment by cweagans** [comment]
@jrthrawny would be the one to answer this. I'm no longer at the company where that code lives.

**Comment by nbarbettini** [comment]
Thanks (and sorry for the delay!). The reason we don't include the Authentication API (`/authn`) in this library is because it is works differently than the CRUD APIs that this library works with. In other languages, we've built a separate SDK for the Authentication API which keeps things modular and clean.

We'll close this for now, but I'd love to learn more about what you're working on @samjarrett. Are you building a web server in Go that needs to call `/authn`?
