### ISSUE TITLE
Incorrectly implemented structs referenced by OpenIdConnectApplicationSettingsClient

### ISSUE THREAD

**Issue by maxschae4** [okta/okta-sdk-golang#85]
While #84 resolved some issues, it has created others.

The OIDC application settings client now references incorrectly generated (empty) structs in 2 places (at least):
https://github.com/okta/okta-sdk-golang/pull/84/files#diff-bd3793555aadda0f07dcbf797d78bb2d
https://github.com/okta/okta-sdk-golang/blob/72580031ba7c471089201e8ccd4050013d6d7d94/okta/openIdConnectApplicationSettingsClient.go#L27 https://github.com/okta/okta-sdk-golang/blob/72580031ba7c471089201e8ccd4050013d6d7d94/okta/oAuthGrantType.go#L23-L24 and
https://github.com/okta/okta-sdk-golang/blob/72580031ba7c471089201e8ccd4050013d6d7d94/okta/openIdConnectApplicationSettingsClient.go#L32

https://github.com/okta/okta-sdk-golang/blob/72580031ba7c471089201e8ccd4050013d6d7d94/okta/oAuthResponseType.go#L23-L24

It seems likely that this is due to an error in the openapi/spec.json:
https://github.com/okta/okta-sdk-golang/blob/72580031ba7c471089201e8ccd4050013d6d7d94/openapi/spec.json#L5410-L5433

Reverting the change to that file would make this usable as it worked prior to this release.

n.b.: This may also apply to the changes for logAuthenticationContext.go
https://github.com/okta/okta-sdk-golang/blob/72580031ba7c471089201e8ccd4050013d6d7d94/okta/logAuthenticationContext.go#L26-L27 as both of those are also empty structs.

**Comment by lmatter** [comment]
I had to change the types to just `string`, as apposed to `[]string` in the commit diff.  Otherwise I would get `cannot unmarshal string into Go struct field LogAuthenticationContext.credentialType of type []*okta.LogCredentialType`

**Comment by bretterer** [comment]
@maxschae4 & @lmatter - We will be updating the Golang SDK soon, and we will address these issues at that time.  Thank you for the PR, as it will more than likely be included in the update.

I do not have a definitive time this will be finished, so please keep an eye on this ticket for updates.

**Comment by goblain** [comment]
@bretterer "We will be updating the Golang SDK soon" - how soon is soon ? this actually blocks us from writing integration with okta in our apps provisioning agent.

**Comment by chrismorris-okta** [comment]
@goblain We are currently in the middle of developing a major release for this SDK. The upcoming version should be released in the next month or so. Given the extensive changes in that version it's possible the issue may be resolved. If it’s not resolved in that release, we’ll certainly look to include this fix in a follow-up release shortly thereafter.

Unfortunately, I'm not able to provide specific dates because it's hard to predict exactly when things are shippable but I hope this helps. 

I'm really sorry to hear that this is a blocker for your project. If this timeline impacts a project you are working on you should reach out to your Okta CSM or developer@okta.com. They can assist with figuring out alternative options.

**Comment by goblain** [comment]
this bug is still present in `sdk_v2`

**Comment by bretterer** [comment]
@goblain this should now be addressed in the official v2 release that is on master.  

These objects are treated as `type string` now which should solve the problems you were having

**Comment by bretterer** [comment]
Closing this as stale.  If you are still experiencing an issue, please feel free to open a new issue and we will get back to you.
